// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { QueryEventsData, QueryEventsErrors, QueryEventsResponses, QueryNeighborsBatchData, QueryNeighborsBatchErrors, QueryNeighborsBatchResponses, QueryNeighborsData, QueryNeighborsErrors, QueryNeighborsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Query Events
 */
export const queryEvents = <ThrowOnError extends boolean = false>(options?: Options<QueryEventsData, ThrowOnError>) => (options?.client ?? client).get<QueryEventsResponses, QueryEventsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/events/query',
    ...options
});

/**
 * Query Neighbors
 */
export const queryNeighbors = <ThrowOnError extends boolean = false>(options: Options<QueryNeighborsData, ThrowOnError>) => (options.client ?? client).get<QueryNeighborsResponses, QueryNeighborsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/entity/neighbors',
    ...options
});

/**
 * Query Neighbors Batch
 */
export const queryNeighborsBatch = <ThrowOnError extends boolean = false>(options?: Options<QueryNeighborsBatchData, ThrowOnError>) => (options?.client ?? client).get<QueryNeighborsBatchResponses, QueryNeighborsBatchErrors, ThrowOnError>({
    responseType: 'json',
    url: '/entities/neighbors',
    ...options
});
