// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Event
 *
 * Represents an event.
 */
export type Event = {
    /**
     * Type
     *
     * Type of event
     */
    type?: string | null;
    /**
     * Location of the event
     */
    location?: LocationData | null;
    /**
     * Title
     *
     * Title of the event. Keep it short and clear.
     */
    title?: string | null;
    /**
     * Description
     *
     * Brief description of the event. Keep it short and clear.
     */
    description?: string | null;
    /**
     * Happened At
     *
     * Timestamp when the event happened
     */
    happened_at?: number | null;
    /**
     * Tags
     *
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Attributes
     *
     * Additional attributes
     */
    attributes?: {
        [key: string]: unknown;
    } | null;
    /**
     * Owner
     *
     * Owner of the document
     */
    owner?: string;
    /**
     * Read
     *
     * Users/Roles with read access
     */
    read?: Array<string>;
    /**
     * Write
     *
     * Users/Roles with write access
     */
    write?: Array<string>;
    /**
     * Id
     *
     * ArangoDB document ID
     */
    _id?: string | null;
    /**
     * Key
     *
     * ArangoDB document key
     */
    _key?: string | null;
    /**
     * Rev
     *
     * ArangoDB document revision
     */
    _rev?: string | null;
    /**
     * Created At
     *
     * Data creation timestamp
     */
    created_at?: number | null;
    /**
     * Updated At
     *
     * Data update timestamp
     */
    updated_at?: number | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LocationData
 *
 * Represents geographical location data.
 */
export type LocationData = {
    /**
     * Latitude
     *
     * Latitude
     */
    latitude: number;
    /**
     * Longitude
     *
     * Longitude
     */
    longitude: number;
    /**
     * Country Code
     *
     * ISO country code
     */
    country_code: string;
    /**
     * Administrative Area
     *
     * Administrative area (e.g., state, province)
     */
    administrative_area: string;
    /**
     * Sub Administrative Area
     *
     * Sub-administrative area
     */
    sub_administrative_area?: string;
    /**
     * Locality
     *
     * Locality (e.g., city, town)
     */
    locality: string;
    /**
     * Sub Locality
     *
     * Sub-locality
     */
    sub_locality?: string;
    /**
     * Address
     *
     * Full address
     */
    address: string;
    /**
     * Postal Code
     *
     * Postal code
     */
    postal_code: number;
};

/**
 * NeighborsResponse
 */
export type NeighborsResponse = {
    /**
     * Events
     *
     * A list of events related to the entity.
     */
    events?: Array<Event>;
    /**
     * Sources
     *
     * A list of sources related to the entity.
     */
    sources?: Array<Source>;
    /**
     * Persons
     *
     * A list of persons related to the entity.
     */
    persons?: Array<Person>;
    /**
     * Organizations
     *
     * A list of organizations related to the entity.
     */
    organizations?: Array<Organization>;
    /**
     * Websites
     *
     * A list of websites related to the entity.
     */
    websites?: Array<Website>;
    /**
     * Relations
     *
     * A list of relations related to the entity.
     */
    relations?: Array<Relation>;
    /**
     * Offset
     *
     * The offset from which to start returning results.
     */
    offset?: number;
};

/**
 * Organization
 *
 * Represents an organization.
 */
export type Organization = {
    /**
     * Type
     *
     * Type of organization
     */
    type?: string | null;
    /**
     * Name
     *
     * Name of the organization
     */
    name?: string | null;
    /**
     * Founded At
     *
     * When organization is founded (timestamp)
     */
    founded_at?: number | null;
    /**
     * Discovered At
     *
     * When organization is discovered (timestamp)
     */
    discovered_at?: number | null;
    /**
     * Last Visited
     *
     * When organization is last visited (timestamp)
     */
    last_visited?: number | null;
    /**
     * Tags
     *
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Attributes
     *
     * Additional attributes
     */
    attributes?: {
        [key: string]: unknown;
    } | null;
    /**
     * Owner
     *
     * Owner of the document
     */
    owner?: string;
    /**
     * Read
     *
     * Users/Roles with read access
     */
    read?: Array<string>;
    /**
     * Write
     *
     * Users/Roles with write access
     */
    write?: Array<string>;
    /**
     * Id
     *
     * ArangoDB document ID
     */
    _id?: string | null;
    /**
     * Key
     *
     * ArangoDB document key
     */
    _key?: string | null;
    /**
     * Rev
     *
     * ArangoDB document revision
     */
    _rev?: string | null;
    /**
     * Created At
     *
     * Data creation timestamp
     */
    created_at?: number | null;
    /**
     * Updated At
     *
     * Data update timestamp
     */
    updated_at?: number | null;
};

/**
 * Person
 *
 * Represents a person.
 */
export type Person = {
    /**
     * Type
     *
     * Role type of person
     */
    type?: string | null;
    /**
     * Role
     *
     * Role
     */
    role?: string | null;
    /**
     * Name
     *
     * Name
     */
    name?: string | null;
    /**
     * Nationality
     *
     * Nationality
     */
    nationality?: string | null;
    /**
     * Birth Date
     *
     * Person's birth date (timestamp)
     */
    birth_date?: number | null;
    /**
     * Tags
     *
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Aliases
     *
     * Aliases
     */
    aliases?: Array<string> | null;
    /**
     * Attributes
     *
     * Additional attributes
     */
    attributes?: {
        [key: string]: unknown;
    } | null;
    /**
     * Owner
     *
     * Owner of the document
     */
    owner?: string;
    /**
     * Read
     *
     * Users/Roles with read access
     */
    read?: Array<string>;
    /**
     * Write
     *
     * Users/Roles with write access
     */
    write?: Array<string>;
    /**
     * Id
     *
     * ArangoDB document ID
     */
    _id?: string | null;
    /**
     * Key
     *
     * ArangoDB document key
     */
    _key?: string | null;
    /**
     * Rev
     *
     * ArangoDB document revision
     */
    _rev?: string | null;
    /**
     * Created At
     *
     * Data creation timestamp
     */
    created_at?: number | null;
    /**
     * Updated At
     *
     * Data update timestamp
     */
    updated_at?: number | null;
};

/**
 * QueryResponse
 */
export type QueryResponse = {
    /**
     * Events
     *
     * A list of events that match the query.
     */
    events?: Array<Event>;
    /**
     * Relations
     *
     * A list of relations that match the query.
     */
    relations?: Array<Relation>;
    /**
     * Offset
     *
     * The offset from which to start returning results.
     */
    offset?: number;
};

/**
 * Relation
 *
 * Represents a relationship between two entities.
 */
export type Relation = {
    /**
     * Name
     *
     * Name of the relation used in database key (must be ascii letters)
     */
    name?: string | null;
    /**
     * Confidence
     *
     * Confidence score
     */
    confidence?: number | null;
    /**
     * Label
     *
     * Label name of the relation (can be any language) to display
     */
    label?: string | null;
    /**
     * Attributes
     *
     * Additional attributes
     */
    attributes?: {
        [key: string]: unknown;
    } | null;
    /**
     * From
     *
     * Source document ID
     */
    _from?: string | null;
    /**
     * To
     *
     * Target document ID
     */
    _to?: string | null;
    /**
     * Owner
     *
     * Owner of the document
     */
    owner?: string;
    /**
     * Read
     *
     * Users/Roles with read access
     */
    read?: Array<string>;
    /**
     * Write
     *
     * Users/Roles with write access
     */
    write?: Array<string>;
    /**
     * Id
     *
     * ArangoDB document ID
     */
    _id?: string | null;
    /**
     * Key
     *
     * ArangoDB document key
     */
    _key?: string | null;
    /**
     * Rev
     *
     * ArangoDB document revision
     */
    _rev?: string | null;
    /**
     * Created At
     *
     * Data creation timestamp
     */
    created_at?: number | null;
    /**
     * Updated At
     *
     * Data update timestamp
     */
    updated_at?: number | null;
};

/**
 * Source
 *
 * Represents a source of information.
 */
export type Source = {
    /**
     * Type
     *
     * Type of source
     */
    type?: string | null;
    /**
     * Url
     *
     * URL
     */
    url?: string | null;
    /**
     * Name
     *
     * Name of the source
     */
    name?: string | null;
    /**
     * Title
     *
     * Title of the source. Keep it short and clear.
     */
    title?: string | null;
    /**
     * Description
     *
     * Brief description of the source. Keep it short and clear.
     */
    description?: string | null;
    /**
     * Reliability
     *
     * Reliability score
     */
    reliability?: number | null;
    /**
     * Tags
     *
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Attributes
     *
     * Additional attributes
     */
    attributes?: {
        [key: string]: unknown;
    } | null;
    /**
     * Owner
     *
     * Owner of the document
     */
    owner?: string;
    /**
     * Read
     *
     * Users/Roles with read access
     */
    read?: Array<string>;
    /**
     * Write
     *
     * Users/Roles with write access
     */
    write?: Array<string>;
    /**
     * Id
     *
     * ArangoDB document ID
     */
    _id?: string | null;
    /**
     * Key
     *
     * ArangoDB document key
     */
    _key?: string | null;
    /**
     * Rev
     *
     * ArangoDB document revision
     */
    _rev?: string | null;
    /**
     * Created At
     *
     * Data creation timestamp
     */
    created_at?: number | null;
    /**
     * Updated At
     *
     * Data update timestamp
     */
    updated_at?: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Website
 *
 * Represents a website.
 */
export type Website = {
    /**
     * Type
     *
     * Type of website
     */
    type?: string | null;
    /**
     * Url
     *
     * URL
     */
    url?: string | null;
    /**
     * Title
     *
     * Title of the website. Keep it short and clear.
     */
    title?: string | null;
    /**
     * Description
     *
     * Brief description of the website. Keep it short and clear.
     */
    description?: string | null;
    /**
     * Founded At
     *
     * When website is founded (timestamp)
     */
    founded_at?: number | null;
    /**
     * Discovered At
     *
     * When website is discovered (timestamp)
     */
    discovered_at?: number | null;
    /**
     * Last Visited
     *
     * When website is last visited (timestamp)
     */
    last_visited?: number | null;
    /**
     * Tags
     *
     * Tags
     */
    tags?: Array<string> | null;
    /**
     * Attributes
     *
     * Additional attributes
     */
    attributes?: {
        [key: string]: unknown;
    } | null;
    /**
     * Owner
     *
     * Owner of the document
     */
    owner?: string;
    /**
     * Read
     *
     * Users/Roles with read access
     */
    read?: Array<string>;
    /**
     * Write
     *
     * Users/Roles with write access
     */
    write?: Array<string>;
    /**
     * Id
     *
     * ArangoDB document ID
     */
    _id?: string | null;
    /**
     * Key
     *
     * ArangoDB document key
     */
    _key?: string | null;
    /**
     * Rev
     *
     * ArangoDB document revision
     */
    _rev?: string | null;
    /**
     * Created At
     *
     * Data creation timestamp
     */
    created_at?: number | null;
    /**
     * Updated At
     *
     * Data update timestamp
     */
    updated_at?: number | null;
};

export type QueryEventsData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Query
         *
         * The search query string.
         */
        query?: string | null;
        /**
         * Date Start
         *
         * The start of the date range for the query.
         */
        date_start?: number | null;
        /**
         * Date End
         *
         * The end of the date range for the query.
         */
        date_end?: number | null;
        /**
         * Country Code
         *
         * The country code to filter the query by.
         */
        country_code?: string | null;
        /**
         * Limit
         *
         * The maximum number of results to return.
         */
        limit?: number;
        /**
         * Offset
         *
         * The offset from which to start returning results.
         */
        offset?: number;
    };
    url: '/events/query';
};

export type QueryEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type QueryEventsError = QueryEventsErrors[keyof QueryEventsErrors];

export type QueryEventsResponses = {
    /**
     * Successful Response
     */
    200: QueryResponse;
};

export type QueryEventsResponse = QueryEventsResponses[keyof QueryEventsResponses];

export type QueryNeighborsData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Id
         *
         * The ArangoDB Document ID (e.g., collection/123)
         */
        id: string;
        /**
         * Limit
         *
         * The maximum number of results to return.
         */
        limit?: number;
        /**
         * Offset
         *
         * The offset from which to start returning results.
         */
        offset?: number;
        /**
         * Include
         *
         * A list of entity types to include.
         */
        include?: Array<string>;
        /**
         * Exclude
         *
         * A list of entity types to exclude.
         */
        exclude?: Array<string>;
    };
    url: '/entity/neighbors';
};

export type QueryNeighborsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type QueryNeighborsError = QueryNeighborsErrors[keyof QueryNeighborsErrors];

export type QueryNeighborsResponses = {
    /**
     * Successful Response
     */
    200: NeighborsResponse;
};

export type QueryNeighborsResponse = QueryNeighborsResponses[keyof QueryNeighborsResponses];

export type QueryNeighborsBatchData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Ids
         *
         * A list of entity IDs to query neighbors for.
         */
        ids?: Array<string>;
        /**
         * Limit
         *
         * The maximum number of results to return.
         */
        limit?: number;
        /**
         * Offset
         *
         * The offset from which to start returning results.
         */
        offset?: number;
        /**
         * Include
         *
         * A list of entity types to include.
         */
        include?: Array<string>;
        /**
         * Exclude
         *
         * A list of entity types to exclude.
         */
        exclude?: Array<string>;
    };
    url: '/entities/neighbors';
};

export type QueryNeighborsBatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type QueryNeighborsBatchError = QueryNeighborsBatchErrors[keyof QueryNeighborsBatchErrors];

export type QueryNeighborsBatchResponses = {
    /**
     * Successful Response
     */
    200: NeighborsResponse;
};

export type QueryNeighborsBatchResponse = QueryNeighborsBatchResponses[keyof QueryNeighborsBatchResponses];
